export const DEMO_MARKETS = [
  { id: "skinport", name: "Skinport", shortName: "SP", region: "Европа · Global", website: "skinport.com" },
  { id: "csfloat", name: "CSFloat", shortName: "CF", region: "Global", website: "csfloat.com" },
  { id: "dmarket", name: "DMarket", shortName: "DM", region: "Global", website: "dmarket.com" },
  { id: "buff163", name: "BUFF Market", shortName: "BF", region: "Азия · Global", website: "buff.market" },
  { id: "skinbaron", name: "SkinBaron", shortName: "SB", region: "Европа", website: "skinbaron.de" },
  { id: "tradeit", name: "Tradeit", shortName: "TI", region: "Global", website: "tradeit.gg" },
  { id: "lisskins", name: "Lis-Skins", shortName: "LS", region: "Европа · СНГ", website: "lis-skins.com" },
  { id: "skinsmonkey", name: "SkinsMonkey", shortName: "SM", region: "Global", website: "skinsmonkey.com" },
] as const;

export const DEMO_ITEMS = [
  {
    slug: "ak-47-redline-field-tested",
    name: "AK-47 | Redline (Field-Tested)",
    weapon: "AK-47",
    skin: "Redline",
    category: "Винтовки",
    rarity: "Засекреченное",
    collection: "Коллекция Phoenix",
    wear: "После полевых испытаний",
    stattrak: false,
    souvenir: false,
    paintSeed: 713,
    floatValue: 0.241863,
    demand: 96,
    change24h: 3.42,
    artTheme: "crimson",
    basePrice: 21.45,
  },
  {
    slug: "awp-asiimov-field-tested",
    name: "AWP | Asiimov (Field-Tested)",
    weapon: "AWP",
    skin: "Asiimov",
    category: "Винтовки",
    rarity: "Тайное",
    collection: "Коллекция Phoenix",
    wear: "После полевых испытаний",
    stattrak: false,
    souvenir: false,
    paintSeed: 491,
    floatValue: 0.276381,
    demand: 92,
    change24h: 1.86,
    artTheme: "arctic",
    basePrice: 112.8,
  },
  {
    slug: "m4a1-s-printstream-minimal-wear",
    name: "M4A1-S | Printstream (Minimal Wear)",
    weapon: "M4A1-S",
    skin: "Printstream",
    category: "Винтовки",
    rarity: "Тайное",
    collection: "Коллекция Broken Fang",
    wear: "Немного поношенное",
    stattrak: false,
    souvenir: false,
    paintSeed: 128,
    floatValue: 0.083912,
    demand: 89,
    change24h: -0.74,
    artTheme: "pearl",
    basePrice: 188.5,
  },
  {
    slug: "karambit-doppler-factory-new",
    name: "Karambit | Doppler (Factory New)",
    weapon: "Karambit",
    skin: "Doppler",
    category: "Ножи",
    rarity: "Тайное",
    collection: "Коллекция Chroma",
    wear: "Прямо с завода",
    stattrak: false,
    souvenir: false,
    paintSeed: 612,
    floatValue: 0.021446,
    demand: 98,
    change24h: 4.18,
    artTheme: "violet",
    basePrice: 1548.2,
  },
  {
    slug: "butterfly-fade-factory-new",
    name: "Butterfly Knife | Fade (Factory New)",
    weapon: "Butterfly Knife",
    skin: "Fade",
    category: "Ножи",
    rarity: "Тайное",
    collection: "Коллекция Dreams & Nightmares",
    wear: "Прямо с завода",
    stattrak: false,
    souvenir: false,
    paintSeed: 412,
    floatValue: 0.008361,
    demand: 95,
    change24h: 2.73,
    artTheme: "sunset",
    basePrice: 2850,
  },
  {
    slug: "desert-eagle-blaze-factory-new",
    name: "Desert Eagle | Blaze (Factory New)",
    weapon: "Desert Eagle",
    skin: "Blaze",
    category: "Пистолеты",
    rarity: "Запрещённое",
    collection: "Коллекция Dust",
    wear: "Прямо с завода",
    stattrak: false,
    souvenir: false,
    paintSeed: 36,
    floatValue: 0.011283,
    demand: 84,
    change24h: 0.92,
    artTheme: "gold",
    basePrice: 788,
  },
  {
    slug: "usp-s-kill-confirmed-minimal-wear",
    name: "USP-S | Kill Confirmed (Minimal Wear)",
    weapon: "USP-S",
    skin: "Kill Confirmed",
    category: "Пистолеты",
    rarity: "Тайное",
    collection: "Коллекция Shadow",
    wear: "Немного поношенное",
    stattrak: false,
    souvenir: false,
    paintSeed: 228,
    floatValue: 0.094216,
    demand: 82,
    change24h: -1.12,
    artTheme: "magenta",
    basePrice: 104.25,
  },
  {
    slug: "stattrak-ak-47-slate-minimal-wear",
    name: "StatTrak™ AK-47 | Slate (Minimal Wear)",
    weapon: "AK-47",
    skin: "Slate",
    category: "Винтовки",
    rarity: "Запрещённое",
    collection: "Коллекция Snakebite",
    wear: "Немного поношенное",
    stattrak: true,
    souvenir: false,
    paintSeed: 507,
    floatValue: 0.102775,
    demand: 76,
    change24h: 5.34,
    artTheme: "graphite",
    basePrice: 25.9,
  },
  {
    slug: "glock-18-gamma-doppler-factory-new",
    name: "Glock-18 | Gamma Doppler (Factory New)",
    weapon: "Glock-18",
    skin: "Gamma Doppler",
    category: "Пистолеты",
    rarity: "Тайное",
    collection: "Коллекция Gamma",
    wear: "Прямо с завода",
    stattrak: false,
    souvenir: false,
    paintSeed: 638,
    floatValue: 0.019621,
    demand: 81,
    change24h: 2.11,
    artTheme: "emerald",
    basePrice: 385,
  },
  {
    slug: "m4a4-howl-field-tested",
    name: "M4A4 | Howl (Field-Tested)",
    weapon: "M4A4",
    skin: "Howl",
    category: "Винтовки",
    rarity: "Контрабандное",
    collection: "Коллекция Huntsman",
    wear: "После полевых испытаний",
    stattrak: false,
    souvenir: false,
    paintSeed: 317,
    floatValue: 0.238906,
    demand: 87,
    change24h: 6.28,
    artTheme: "ember",
    basePrice: 5230,
  },
  {
    slug: "awp-lightning-strike-minimal-wear",
    name: "AWP | Lightning Strike (Minimal Wear)",
    weapon: "AWP",
    skin: "Lightning Strike",
    category: "Винтовки",
    rarity: "Тайное",
    collection: "Коллекция Arms Deal",
    wear: "Немного поношенное",
    stattrak: false,
    souvenir: false,
    paintSeed: 75,
    floatValue: 0.073218,
    demand: 72,
    change24h: -2.31,
    artTheme: "cobalt",
    basePrice: 655,
  },
  {
    slug: "sport-gloves-vice-field-tested",
    name: "Sport Gloves | Vice (Field-Tested)",
    weapon: "Sport Gloves",
    skin: "Vice",
    category: "Перчатки",
    rarity: "Тайное",
    collection: "Коллекция Glove",
    wear: "После полевых испытаний",
    stattrak: false,
    souvenir: false,
    paintSeed: 327,
    floatValue: 0.267731,
    demand: 79,
    change24h: 1.24,
    artTheme: "candy",
    basePrice: 1220,
  },
  {
    slug: "souvenir-awp-desert-hydra-field-tested",
    name: "Souvenir AWP | Desert Hydra (Field-Tested)",
    weapon: "AWP",
    skin: "Desert Hydra",
    category: "Винтовки",
    rarity: "Тайное",
    collection: "Коллекция 2021 Mirage",
    wear: "После полевых испытаний",
    stattrak: false,
    souvenir: true,
    paintSeed: 913,
    floatValue: 0.246032,
    demand: 68,
    change24h: 3.06,
    artTheme: "sand",
    basePrice: 2460,
  },
] as const;

export function makeHistoryRows(itemId: number, itemIndex: number, basePrice: number) {
  const rows: { itemId: number; recordedOn: string; lowPrice: string; medianPrice: string; volume: number; isDemo: boolean }[] = [];
  const now = new Date();
  const phase = (itemIndex + 1) * 0.73;

  for (let day = 364; day >= 0; day -= 1) {
    const recorded = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() - day));
    const progress = (364 - day) / 364;
    const trend = 0.92 + progress * 0.08;
    const wave = 0.035 * (Math.sin(progress * Math.PI * 6 + phase) - Math.sin(phase));
    const median = basePrice * (trend + wave);
    const low = median * (0.947 + ((itemIndex + day) % 5) * 0.006);
    const volume = Math.max(2, Math.round((18 + itemIndex * 2) * (0.65 + Math.abs(Math.sin(day * 0.17 + phase)) * 0.9)));

    rows.push({
      itemId,
      recordedOn: recorded.toISOString().slice(0, 10),
      lowPrice: low.toFixed(2),
      medianPrice: median.toFixed(2),
      volume,
      isDemo: true,
    });
  }

  return rows;
}

export function makeListingRows(itemId: number, itemIndex: number, basePrice: number) {
  return DEMO_MARKETS.map((market, marketIndex) => {
    const spread = 0.964 + marketIndex * 0.008 + ((itemIndex * 7 + marketIndex * 5) % 9) * 0.0015;
    const buyerPrice = basePrice * spread;
    const modeledPayout = buyerPrice * (0.91 - (marketIndex % 4) * 0.012);
    const hoursAgo = (itemIndex * 3 + marketIndex * 2) % 8;

    return {
      sourceKey: `demo:${itemId}:${market.id}`,
      itemId,
      marketId: market.id,
      buyerPrice: buyerPrice.toFixed(2),
      sellerPayout: modeledPayout.toFixed(2),
      currency: "USD",
      region: market.region,
      capturedAt: new Date(Date.now() - hoursAgo * 60 * 60 * 1000),
      isDemo: true,
    };
  });
}
